In [1]:
conda install numpy

Solving environment: ...working... done

# All requested packages already installed.

Note: you may need to restart the kernel to use updated packages.



==> WARNING: A newer version of conda exists. <==
  current version: 4.10.1
  latest version: 23.5.2

Please update conda by running

    $ conda update -n base -c defaults conda




In [2]:
import numpy as np

# NUMPY - Numerical Analysis and Calculations

In [3]:
print('hi')

hi


In [4]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
b=np.array([[10,20,30],[40,50,60],[12,23,34],[21,32,43]])
print(b)

[[10 20 30]
 [40 50 60]
 [12 23 34]
 [21 32 43]]


In [6]:
c=np.zeros(3)
print(c)

[0. 0. 0.]


In [7]:
d=np.ones(4)
print(d)

[1. 1. 1. 1.]


In [8]:
e=np.arange(5)
print(e)

[0 1 2 3 4]


In [9]:
f=np.arange(1,11,2)
print(f)

[1 3 5 7 9]


In [10]:
print(np.ones(4,dtype=np.int64))

[1 1 1 1]


In [11]:
g=np.linspace(0,10,num=3)
print(g)

[ 0.  5. 10.]


In [12]:
print(np.linspace(1,100,num=50,dtype=np.int64))

[  1   3   5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35
  37  39  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71
  73  75  77  79  81  83  85  87  89  91  93  95  97 100]


In [13]:
print(np.shape(g))

(3,)


In [14]:
print(np.ndim(e))

1


In [15]:
print(np.empty(2))

[ 5. 10.]


In [16]:
print(np.shape(b))
print(np.size(b))

(4, 3)
12


In [17]:
print(np.empty(3))

[ 0.  5. 10.]


In [18]:
x=np.arange(6)
print(x)

[0 1 2 3 4 5]


In [19]:
y=x.reshape(2,3)
print(y)

[[0 1 2]
 [3 4 5]]


In [20]:
m=np.array([[1,2,3]])
n=np.array([[100,200,300]])
print(np.concatenate((m,n),axis=0))

[[  1   2   3]
 [100 200 300]]


In [21]:
print(np.concatenate((a,c),axis=0))

[1. 2. 3. 0. 0. 0.]


In [22]:
print(m[0])

[1 2 3]


In [23]:
print(np.repeat(g,2))

[ 0.  0.  5.  5. 10. 10.]


In [24]:
print(np.tile(g,2))

[ 0.  5. 10.  0.  5. 10.]


In [25]:
arr=np.array([1,45,32,67,23,10])
print(arr)

[ 1 45 32 67 23 10]


In [26]:
print(np.sort(arr))

[ 1 10 23 32 45 67]


In [27]:
arr[1]

45

In [28]:
arr[1:7]

array([45, 32, 67, 23, 10])

In [29]:
print(arr[arr>4])

[45 32 67 23 10]


In [30]:
arr1=np.array([1,2,3,4,5,6,7])
print(arr1)

[1 2 3 4 5 6 7]


In [31]:
con=arr1[(arr1>1)&(arr1<5)]
print(con)

[2 3 4]


In [32]:
cond=arr1[(arr1>1)|(arr1<5)]
print(cond)

[1 2 3 4 5 6 7]


In [33]:
print(arr1[arr1%5==0])

[5]


 # PANDAS

In [34]:
conda install pandas


Note: you may need to restart the kernel to use updated packages.




==> WARNING: A newer version of conda exists. <==
  current version: 4.10.1
  latest version: 23.5.2

Please update conda by running

    $ conda update -n base -c defaults conda




Solving environment: ...working... done

# All requested packages already installed.



In [35]:
import pandas as pd

In [36]:
aa=pd.Series([1,2,3,4,5])
aa

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [37]:
date=pd.date_range("20230721",periods=11)
date

DatetimeIndex(['2023-07-21', '2023-07-22', '2023-07-23', '2023-07-24',
               '2023-07-25', '2023-07-26', '2023-07-27', '2023-07-28',
               '2023-07-29', '2023-07-30', '2023-07-31'],
              dtype='datetime64[ns]', freq='D')

In [39]:
df=pd.DataFrame(np.random.randn(2,3),dtype=np.int8)
df

0  1  2
0  0  0  0
1 -2  1  0

In [73]:
df1=pd.DataFrame(
{
    "A":(1.0,2.0,3.0,4.0,5.0),
    "B":pd.date_range("20230721",periods=5),
    "C":pd.Series([0,2,3,4,5],index=list(range(5))),
    
}
)
df1
    

A          B  C
0  1.0 2023-07-21  0
1  2.0 2023-07-22  2
2  3.0 2023-07-23  3
3  4.0 2023-07-24  4
4  5.0 2023-07-25  5

In [74]:
df1.describe()

A         C
count  5.000000  5.000000
mean   3.000000  2.800000
std    1.581139  1.923538
min    1.000000  0.000000
25%    2.000000  2.000000
50%    3.000000  3.000000
75%    4.000000  4.000000
max    5.000000  5.000000

In [51]:
df1['A']

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
Name: A, dtype: float64

In [52]:
df1['B']

0   2023-07-21
1   2023-07-22
2   2023-07-23
3   2023-07-24
4   2023-07-25
Name: B, dtype: datetime64[ns]

In [61]:
df1.iloc[0:2]

A          B  C
0  1.0 2023-07-21  1
1  2.0 2023-07-22  2

In [62]:
df1.loc[0:2]

A          B  C
0  1.0 2023-07-21  1
1  2.0 2023-07-22  2
2  3.0 2023-07-23  3

In [65]:
df1.loc['A':'C']

Empty DataFrame
Columns: [A, B, C]
Index: []

In [75]:
np.isnan(df1)

A      B      C
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False

In [78]:
pd.isna(df1)

A      B      C
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False

In [79]:
df1.fillna(value=5)

A          B  C
0  1.0 2023-07-21  0
1  2.0 2023-07-22  2
2  3.0 2023-07-23  3
3  4.0 2023-07-24  4
4  5.0 2023-07-25  5

In [81]:
df1.dropna()

A          B  C
0  1.0 2023-07-21  0
1  2.0 2023-07-22  2
2  3.0 2023-07-23  3
3  4.0 2023-07-24  4
4  5.0 2023-07-25  5